services:
  init:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.jellyfin
    restart: "no"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - cloud_jellyfin_config:/etc/jellyfin
      - cloud_jellyfin_cache:/var/cache/jellyfin
      - cloud_jellyfin_data:/var/lib/jellyfin

  baikal:
    image: ckulka/baikal:0.10.1
    container_name: baikal
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "5234:80"
    volumes:
      - cloud_baikal_config:/var/www/baikal/config
      - cloud_baikal_data:/var/www/baikal/Specific
      - type: bind
        source: ./.local/logs
        target: /logs

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-latest}
    security_opt:
      - no-new-privileges:true
    user: "${PUID:-1000}:${PGID:-1000}"
    depends_on:
      init:
        condition: service_completed_successfully
      rclone:
        condition: service_started
    group_add:
      - "${MEDIA_GID:-3000}"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/logs
    volumes:
      - cloud_jellyfin_cache:/var/cache/jellyfin
      - cloud_jellyfin_config:/etc/jellyfin
      - cloud_jellyfin_data:/var/lib/jellyfin
      - type: bind
        source: ./.local/media
        target: /media
        read_only: true
        bind:
          propagation: rshared
      - type: bind
        source: ./.local/logs
        target: /logs
    ports:
      - "8096:8096"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.minio
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-${S3_ACCESS_KEY}}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-${S3_SECRET_KEY}}
    volumes:
      - cloud_minio_data:/data
      - type: bind
        source: ./.local/logs
        target: /logs
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"

  rclone:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.rclone
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=${PUID:-1000}
      - MEDIA_GID=${MEDIA_GID:-3000}
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    volumes:
      - type: bind
        source: ./.local/media
        target: /media
        bind:
          propagation: rshared
      - ./.local/rclone:/config/rclone:ro
      - type: bind
        source: ./.local/logs
        target: /logs
    devices:
      - /dev/fuse:/dev/fuse

  restic:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.restic
    restart: "no"
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY:-/repo}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD:-just_a_rather_very_important_password}
    volumes:
      - ./.local/restic:/repo
      - ./.local/backups:/backups
    profiles:
      - on-demand

volumes:
  cloud_baikal_config:
    name: "${PROJECT_NAME:-cloud}_baikal_config"
  cloud_baikal_data:
    name: "${PROJECT_NAME:-cloud}_baikal_data"
  cloud_jellyfin_config:
    name: "${PROJECT_NAME:-cloud}_jellyfin_config"
  cloud_jellyfin_cache:
    name: "${PROJECT_NAME:-cloud}_jellyfin_cache"
  cloud_jellyfin_data:
    name: "${PROJECT_NAME:-cloud}_jellyfin_data"
  cloud_minio_data:
    name: "${PROJECT_NAME:-cloud}_minio_data"
