---
- name: Template service files
  become: true
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ unit.name }}.service"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ units }}"
  loop_control:
    loop_var: unit
  notify: Reload systemd

- name: Template timer files
  become: true
  ansible.builtin.template:
    src: timer.j2
    dest: "/etc/systemd/system/{{ unit.name }}.timer"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ units }}"
  loop_control:
    loop_var: unit
  notify: Reload systemd

- name: Enable and start timers
  become: true
  ansible.builtin.systemd:
    name: "{{ unit.name }}.timer"
    enabled: true
    state: started
    daemon_reload: true
  loop: "{{ units }}"
  loop_control:
    loop_var: unit
