from typing import Protocol


class HealthProberPort(Protocol):
    def check_docker(self) -> bool: ...
    def check_containers(self, names: list[str]) -> dict[str, bool]: ...
    def run_all(self) -> None: ...
