from typing import Protocol


class ResticRunnerPort(Protocol):
    def ensure_repo(self) -> None: ...
    def run_backup(self, _excludes: list[str], target: str) -> None: ...
    def run_restore(self, snapshot: str, target: str) -> None: ...
    def list_snapshots(self) -> list[dict]: ...
    def push_to_remote(self, remote: str) -> None: ...
