# cspell:words rprivate

services:
  baikal:
    volumes:
      - ${LOGS_DIR:-./runtime/logs}:/logs

  jellyfin:
    volumes:
      - type: bind
        source: ${MEDIA_DATA_PATH:-./runtime/media}
        target: /media
        read_only: true
        bind:
          propagation: rprivate
      - ${LOGS_DIR:-./runtime/logs}:/logs

  minio:
    volumes:
      - ${LOGS_DIR:-./runtime/logs}:/logs

  rclone:
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - type: bind
        source: ${MEDIA_DATA_PATH:-./runtime/media}
        target: /media
        bind:
          propagation: rprivate
      - rclone_config_data:/config/rclone:ro
      - ${LOGS_DIR:-./runtime/logs}:/logs
volumes:
  rclone_config_data:
    name: "rclone_config"
    external: true
