services:

  baikal:
    volumes:
      - ./.local/logs:/logs

  jellyfin:
    volumes:
      - type: bind
        source: ${MEDIA_DATA_PATH:-./.local/media}
        target: /media
        read_only: true
        bind:
            propagation: ${MEDIA_PROPAGATION:-rshared}
      - ./.local/logs:/logs

  minio:
    volumes:
      - ./.local/logs:/logs


  rclone:
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - type: bind
        source: ${MEDIA_DATA_PATH:-./.local/media}
        target: /media
        bind:
            propagation: ${MEDIA_PROPAGATION:-rshared}
      - type: bind
        source: ./.local/rclone
        target: /config/rclone
        read_only: true
      - ./.local/logs:/logs

  restic:
    volumes:
      - ${RESTIC_REPO_DIR:-restic_repo_data}:/repo
      - ${BACKUPS_DIR:-backups_data}:/backups

volumes:
  restic_repo_data:
    name: "${PROJECT_NAME:-server-apps}_restic"
  backups_data:
    name: "${PROJECT_NAME:-server-apps}_backups"
    external: true
